// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/cecepsprd/starworks-test/internal/model"
	mock "github.com/stretchr/testify/mock"

	sql "database/sql"
)

// WalletRepository is an autogenerated mock type for the WalletRepository type
type WalletRepository struct {
	mock.Mock
}

// AddWallet provides a mock function with given fields: ctx, tx, wallet
func (_m *WalletRepository) AddWallet(ctx context.Context, tx *sql.Tx, wallet model.Wallet) error {
	ret := _m.Called(ctx, tx, wallet)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *sql.Tx, model.Wallet) error); ok {
		r0 = rf(ctx, tx, wallet)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ReadBalance provides a mock function with given fields: ctx, req
func (_m *WalletRepository) ReadBalance(ctx context.Context, req model.CheckBalanceRequest) (*model.Wallet, error) {
	ret := _m.Called(ctx, req)

	var r0 *model.Wallet
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.CheckBalanceRequest) (*model.Wallet, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.CheckBalanceRequest) *model.Wallet); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Wallet)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.CheckBalanceRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateBalance provides a mock function with given fields: _a0, _a1
func (_m *WalletRepository) UpdateBalance(_a0 context.Context, _a1 model.Wallet) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, model.Wallet) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewWalletRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewWalletRepository creates a new instance of WalletRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewWalletRepository(t mockConstructorTestingTNewWalletRepository) *WalletRepository {
	mock := &WalletRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
